-- V2 Seed pays (compatible H2 + PostgreSQL via MERGE)
MERGE INTO pays (code_iso2, code_iso3, nom_fr, nom_en, indicatif_tel)
KEY(code_iso2) VALUES
('AF','AFG','Afghanistan','Afghanistan','+93'),
('ZA','ZAF','Afrique du Sud','South Africa','+27'),
('AL','ALB','Albanie','Albania','+355'),
('DZ','DZA','Algérie','Algeria','+213'),
('DE','DEU','Allemagne','Germany','+49'),
('AO','AGO','Angola','Angola','+244'),
('SA','SAU','Arabie Saoudite','Saudi Arabia','+966'),
('AR','ARG','Argentine','Argentina','+54'),
('AU','AUS','Australie','Australia','+61'),
('AT','AUT','Autriche','Austria','+43'),
('BE','BEL','Belgique','Belgium','+32'),
('BJ','BEN','Bénin','Benin','+229'),
('TD','TCD','Tchad','Chad','+235'),
('BI','BDI','Burundi','Burundi','+257'),
('CM','CMR','Cameroun','Cameroon','+237'),
('CA','CAN','Canada','Canada','+1'),
('CV','CPV','Cap-Vert','Cape Verde','+238'),
('CF','CAF','Rép. Centrafricaine','Central African Republic','+236'),
('KM','COM','Comores','Comoros','+269'),
('CG','COG','Congo','Congo','+242'),
('CD','COD','Congo (RDC)','Congo (DRC)','+243'),
('CI','CIV','Cote d Ivoire','Ivory Coast','+225'),
('HR','HRV','Croatie','Croatia','+385'),
('DK','DNK','Danemark','Denmark','+45'),
('DJ','DJI','Djibouti','Djibouti','+253'),
('EG','EGY','Egypte','Egypt','+20'),
('AE','ARE','Emirats Arabes Unis','United Arab Emirates','+971'),
('ES','ESP','Espagne','Spain','+34'),
('US','USA','Etats-Unis','United States','+1'),
('ET','ETH','Ethiopie','Ethiopia','+251'),
('FI','FIN','Finlande','Finland','+358'),
('FR','FRA','France','France','+33'),
('GA','GAB','Gabon','Gabon','+241'),
('GM','GMB','Gambie','Gambia','+220'),
('GH','GHA','Ghana','Ghana','+233'),
('GN','GIN','Guinee','Guinea','+224'),
('GW','GNB','Guinee-Bissau','Guinea-Bissau','+245'),
('GQ','GNQ','Guinee Equatoriale','Equatorial Guinea','+240'),
('GR','GRC','Grece','Greece','+30'),
('HU','HUN','Hongrie','Hungary','+36'),
('IN','IND','Inde','India','+91'),
('ID','IDN','Indonesie','Indonesia','+62'),
('IR','IRN','Iran','Iran','+98'),
('IQ','IRQ','Irak','Iraq','+964'),
('IE','IRL','Irlande','Ireland','+353'),
('IL','ISR','Israel','Israel','+972'),
('IT','ITA','Italie','Italy','+39'),
('JP','JPN','Japon','Japan','+81'),
('JO','JOR','Jordanie','Jordan','+962'),
('KE','KEN','Kenya','Kenya','+254'),
('KW','KWT','Koweit','Kuwait','+965'),
('LB','LBN','Liban','Lebanon','+961'),
('LR','LBR','Liberia','Liberia','+231'),
('LY','LBY','Libye','Libya','+218'),
('MG','MDG','Madagascar','Madagascar','+261'),
('MW','MWI','Malawi','Malawi','+265'),
('MY','MYS','Malaisie','Malaysia','+60'),
('ML','MLI','Mali','Mali','+223'),
('MA','MAR','Maroc','Morocco','+212'),
('MR','MRT','Mauritanie','Mauritania','+222'),
('MU','MUS','Maurice','Mauritius','+230'),
('MX','MEX','Mexique','Mexico','+52'),
('MZ','MOZ','Mozambique','Mozambique','+258'),
('NA','NAM','Namibie','Namibia','+264'),
('NE','NER','Niger','Niger','+227'),
('NG','NGA','Nigeria','Nigeria','+234'),
('NO','NOR','Norvege','Norway','+47'),
('NL','NLD','Pays-Bas','Netherlands','+31'),
('PK','PAK','Pakistan','Pakistan','+92'),
('PL','POL','Pologne','Poland','+48'),
('PT','PRT','Portugal','Portugal','+351'),
('QA','QAT','Qatar','Qatar','+974'),
('RW','RWA','Rwanda','Rwanda','+250'),
('SN','SEN','Senegal','Senegal','+221'),
('SL','SLE','Sierra Leone','Sierra Leone','+232'),
('SO','SOM','Somalie','Somalia','+252'),
('SD','SDN','Soudan','Sudan','+249'),
('SS','SSD','Soudan du Sud','South Sudan','+211'),
('SE','SWE','Suede','Sweden','+46'),
('CH','CHE','Suisse','Switzerland','+41'),
('SZ','SWZ','Eswatini','Eswatini','+268'),
('TZ','TZA','Tanzanie','Tanzania','+255'),
('TD','TCD','Tchad','Chad','+235'),
('TG','TGO','Togo','Togo','+228'),
('TN','TUN','Tunisie','Tunisia','+216'),
('TR','TUR','Turquie','Turkey','+90'),
('UG','UGA','Ouganda','Uganda','+256'),
('UA','UKR','Ukraine','Ukraine','+380'),
('GB','GBR','Royaume-Uni','United Kingdom','+44'),
('RU','RUS','Russie','Russia','+7'),
('CN','CHN','Chine','China','+86'),
('KR','KOR','Coree du Sud','South Korea','+82'),
('BR','BRA','Bresil','Brazil','+55'),
('ZM','ZMB','Zambie','Zambia','+260'),
('ZW','ZWE','Zimbabwe','Zimbabwe','+263');
